---
- name: OS별 변수 로드
  include_vars: "{{ ansible_os_family }}.yml"

- name: 필수 패키지 설치
  package:
    name: "{{ postgres_packages }}"
    state: present

- name: PostgreSQL 서비스 시작 및 활성화
  systemd:
    name: postgresql
    state: started
    enabled: yes

- name: DB 초기화 (Rocky 전용)
  command: postgresql-setup --initdb
  args:
    creates: "{{ pg_data_dir }}/PG_VERSION"
  when: postgres_init

- name: listen_addresses 설정
  lineinfile:
    path: "{{ pg_conf_path }}"
    regexp: "^#?listen_addresses"
    line: "listen_addresses = '*'"
  notify: restart postgresql
# 5. password_encryption (Ubuntu)
- name: password_encryption 설정
  lineinfile:
    path: "{{ pg_conf_path }}"
    regexp: "^#?password_encryption"
    line: "password_encryption = md5"
  notify: restart postgresql

- name: localhost md5 인증 설정
  replace:
    path: "{{ pg_hba_path }}"
    regexp: '^(host\s+all\s+all\s+(127\.0\.0\.1\/32|::1\/128)\s+)(ident|scram-sha-256|trust|peer)$'
    replace: '\1md5'
  notify: restart postgresql

- name: 외부 접속 허용
  lineinfile:
    path: "{{ pg_hba_path }}"
    line: "host     all     all     0.0.0.0/0     md5"
    insertafter: EOF
  notify: restart postgresql

- name: postgres 비밀번호 설정
  postgresql_user:
    name: postgres
    password: "{{ postgres_admin_password }}"
  become: yes
  become_user: postgres

- name: 사용자 생성
  postgresql_user:
    name: "{{ db_user }}"
    password: "{{ db_pass }}"
  become: yes
  become_user: postgres

- name: DB 생성
  postgresql_db:
    name: "{{ db_name }}"
    owner: "{{ db_user }}"
  become: yes
  become_user: postgres