---
- name: "1. RedHat 계열 EPEL 레포지토리 설치"
  dnf:
    name: epel-release
    state: present
  become: yes
  when: 
    - ansible_os_family == "RedHat"
    - "'Amazon' not in ansible_distribution"

- name: "2. RedHat 계열 메타데이터 캐시 업데이트"
  dnf:
    update_cache: yes
  become: yes
  when: ansible_os_family == "RedHat"

- name: "3. 부하 테스트 도구 설치 (stress-ng 및 stress)"
  package:
    name: "{{ item }}"
    state: present
  become: yes
  # 도구 두 개를 리스트로 넣어 하나라도 설치되게 함
  loop:
    - stress-ng
    - stress

- name: "4. Apache Benchmark(ab) 도구 설치"
  package:
    name: "{{ 'apache2-utils' if ansible_os_family == 'Debian' else 'httpd-tools' }}"
    state: present
  become: yes