---
# Service Deployment Role - Main task file

- name: "Service deployment"
  block:
    - name: "Environment Setup"
      include_tasks: setup_env.yml

    - name: "Repository sync"
      include_tasks: repo_sync.yml

    - name: "Process state check"
      include_tasks: process_check.yml

    - name: "Deploy"
      include_tasks: deploy.yml
