db_name: "{{ lookup('env', 'DB_NAME') | default('scott_db', true) }}"
db_user: "{{ lookup('env', 'DB_USER') | default('scott', true) }}"
db_pass: "{{ lookup('env', 'DB_PASS') }}"
postgres_admin_password: "{{ lookup('env', 'POSTGRES_ADMIN_PASSWORD') }}"

pg_version: 16 