- name: 패키지 설치
  apt:
    name:
      - postgresql
      - postgresql-contrib
      - python3-psycopg2
      - acl
    state: present
    update_cache: yes

- name: 1. 서비스 시작 및 활성화
  systemd:
    name: postgresql
    state: started
    enabled: yes

- name: 2. listen_addresses 설정
  lineinfile:
    path: "{{ pg_conf_path }}"
    regexp: "^#?listen_addresses"
    line: "listen_addresses = '*'"

- name: 3. password_encryption 설정
  lineinfile:
    path: "{{ pg_conf_path }}"
    regexp: "^#?password_encryption"
    line: "password_encryption = md5"

- name: 4. localhost md5 접속 허용
  replace:
    path: "{{ pg_hba_path }}"
    regexp: '^(host\s+all\s+all\s+(127\.0\.0\.1\/32|::1\/128)\s+)(ident|scram-sha-256|trust|peer)$'
    replace: '\1md5'

- name: 5. 외부 접속 허용
  lineinfile:
    path: "{{ pg_hba_path }}"
    line: "host     all     all     0.0.0.0/0     md5"
    insertafter: EOF

- name: 6. postgres 비밀번호 설정
  postgresql_user:
    name: postgres
    password: "{{ postgres_password }}"
  become: yes
  become_user: postgres

- name: 7. 사용자 생성
  postgresql_user:
    name: "{{ db_user }}"
    password: "{{ db_pass }}"
  become: yes
  become_user: postgres

- name: 8. DB 생성
  postgresql_db:
    name: "{{ db_name }}"
    owner: "{{ db_user }}"
  become: yes
  become_user: postgres

- name: 9. 서비스 재시작 
  systemd:
    name: postgresql
    state: restarted
