---
# Node Exporter Setup Role Defaults

node_exporter_version: "1.7.0"
node_exporter_user: node_exporter
node_exporter_group: node_exporter
node_exporter_archive_name: "node_exporter-{{ node_exporter_version }}.linux-amd64"
node_exporter_archive_path: "/tmp/node_exporter-{{ node_exporter_version }}.tar.gz"
node_exporter_binary_path: /usr/local/bin/node_exporter
