# ~/ansible/dependency_setup.yml
---
- name: "런타임 의존성 설치"
  hosts: [EC2, On-Premise]
  gather_facts: no
  become: no
  remote_user: "{{ lookup('env', 'BOOTSTRAP_USER') | default('user1', true) }}"

  roles:
    - dependency_setup
