---
- name: "main"
  hosts: localhost

  # 온프레미스 서버 설정 (On_Premise)
- name: "Configure On-Premise Servers"
  hosts: On-Pre
  become: yes
  vars:
    domain_name: "{{ lookup('env', 'TF_VAR_domain_name') }}"
    tunnel_id: "{{ lookup('env', 'ANSIBLE_TUNNEL_ID') }}"
    tunnel_cert_path: "/etc/cloudflared/{{ tunnel_id }}.json"
  roles:
    - role: ec2_bootstrap     
    - role: dependency_setup
    - role: service_deployment

# AWS EC2 인스턴스 설정 (EC2)
- name: "Configure AWS EC2 Instances"
  hosts: EC2
  become: yes
  vars:
    deploy_branch: "main"
    domain_name: "{{ lookup('env', 'TF_VAR_domain_name') }}"
    tunnel_id: "{{ lookup('env', 'ANSIBLE_TUNNEL_ID') }}"
    tunnel_cert_path: "/etc/cloudflared/{{ tunnel_id }}.json"
  environment:
    PATH: "{{ ansible_env.HOME }}/.local/bin:{{ ansible_env.PATH }}"
  roles:
    - role: ec2_bootstrap
    - role: dependency_setup
    - role: service_deployment

# 데이터베이스 서버 설정 (DB)
- name: "Configure Database Servers"
  hosts: DB
  become: yes
  roles:
    - role: postgresql_setup

